FROM debian

MAINTAINER odidukh

RUN apt-get update && apt-get install -y \
      wget \
      build-essential

RUN wget http://download.redis.io/redis-stable.tar.gz
RUN tar xvzf redis-stable.tar.gz

# docker build -t bonus_ex04_app .

# docker run --rm -ti bonus_ex04_app

