#Java_environment

FROM ubuntu

RUN apt-get update && apt-get upgrade -y && apt-get install -y default-jdk default-jre git vim

# docker build -t bonus_ex02_app .

# docker run --rm -ti bonus_ex02_app
